[module]
  [[module.imports]]
    path = "github.com/imfing/hextra"

baseURL = '/'
languageCode = 'en-us'
title = 'Spectest Documentation'
theme = 'github.com/imfing/hextra'

[params]
  description = 'Documentation for Spectest'
  [params.navbar]
    displayTitle = false
    displayLogo = true
    
    [params.navbar.logo]
      path = "https://raw.githubusercontent.com/justiceo/spectest/refs/heads/main/assets/spectest-logo-transparent.png"
      width = 150
      height = 150
      link = "/"

  # Theme configuration
  [params.theme]
    default = "light"        
    displayToggle = true    


  [params.search]
    enable = true

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    pageRef = '/'
    weight = 1

  [[menu.main]]
    identifier = 'docs'
    name = 'Documentation'
    pageRef = '/docs/introduction/'
    weight = 2
