[module]
  [[module.imports]]
    path = "github.com/imfing/hextra"

baseURL = '/'
languageCode = 'en-us'
title = 'Spectest Documentation'
theme = 'github.com/imfing/hextra'

[params]
  logo = 'https://raw.githubusercontent.com/justiceo/spectest/refs/heads/main/assets/spectest-logo-transparent.png'
  description = 'Documentation for Spectest'
   # Remove the old darkMode = true line and replace with:
  [params.theme]
    default = "light"        # This forces light mode as default
    displayToggle = true     # This allows users to toggle if they want


  [params.search]
    enable = true

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    pageRef = '/'
    weight = 1

  [[menu.main]]
    identifier = 'docs'
    name = 'Documentation'
    pageRef = '/docs/introduction/'
    weight = 2
